- customer-config/cloud-core/ccc.demo-test.v1.json
Reverts extenda/hiiretail-json-schema-registry#15
> Revert "chore: update ccc.demo-test.v1.json for demo"

- customer-config/checkout-config/che.business-key-value.v1.json
**JIRA Ticket**: https://jira.extendaretail.com/browse/POS-12743
**Description**: first try to create a key / value schema to store and get POS business properties
> feat(POS-12743): basic schema to store POS business properties

- customer-config/pos-config/pos.config.v1.json
Description: renaming the schema to use "pos" prefix instead of "che"
> feat(POS-12743): changed the schema name for POS configuration

- customer-config/pos-config/pos.config.v1.json
**JIRA Ticket:** https://jira.extendaretail.com/browse/POS-12880
**Description**: new field" id" is added to uniquely identify the configuration point
For example:
{
"key": "/Business/StoreSpecificProperties/Node/BagEan1",
"value": "5999",
"type": "String"
},
will be
{
**"id": "node.bag.ean1"**
"key": "/Business/StoreSpecificProperties/Node/BagEan1",
"value": "5999",
"type": "String"
},
> feat(POS-12880): added id field to the schema

- customer-config/checkout-app/cha.external-websites.v1.json
Proposal
```
{
"items": [
{
"url": "https://www.external.link/1/",
"name": "External Link 1"
},
{
"url": "https://www.external.link/2/",
"name": "External Link 2"
}
]
}
```
> feat: Checkout App external websites schema

- customer-config/checkout-config/che.tender.v1-preview.json
feat(HCC-6774) Add noAutoFinalization flag to Tender schema.
> feat(HCC-6774) Add noAutoFinalization flag to Tender schema.

- customer-config/checkout-config/che.plulist.v2.json
Update due to https://extendaretail.atlassian.net/browse/RM-2942
> feat(HCC-7225): Add sequence number for sorting PLU items and groups

- customer-config/checkout-app/cha.settings.v1.json
[Original PR](https://github.com/extenda/hiiretail-checkout-ui/pull/1255)
> feat(HCC-8042): Add sco lockscreen flag

- customer-config/checkout-app/cha.settings.v1.json
[related changes in hiiretail-checkout-ui](https://github.com/extenda/hiiretail-checkout-ui/pull/1315)
> feat(HCC-8435): SCO lock settings

- customer-config/checkout-app/cha.settings.v1.json
[Related CA changes](https://github.com/extenda/hiiretail-checkout-ui/pull/1483)
> feat(HCC-8868): Expose active receipt layout CCC configuration

- customer-config/attendant-app/att.color-coding.v1.json
- customer-config/attendant-app/att.icon-config.v1.json
- customer-config/attendant-app/att.sound-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1805
> feat(AT-1805): Add config schemas for att app

- customer-config/attendant-app/att.sound-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1805
> fix(AT-1805): Property definition

- customer-config/attendant-app/att.sound-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1805
> fix(AT-1805): Required prop naming

- customer-config/checkout-app/cha.settings.v1.json
[Hii checkout PR](https://github.com/extenda/hiiretail-checkout-ui/pull/1535)
> feat(HCC-9654): POS hot keys

- customer-config/attendant-app/att.icons-config.v1.json
- customer-config/attendant-app/att.sounds-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1906
> feat(AT-1906): Change icon name validation

- customer-config/attendant-app/att.icons-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1906
> fix(AT-1906): Automatically removing escape char in js

- customer-config/attendant-app/att.icons-config.v1.json
issue: https://extendaretail.atlassian.net/browse/AT-1906
> fix(AT-1906): Change customer config icons schema for Att

- customer-config/checkout-app/cha.settings.v1.json
[hiiretail-checkout-ui PR](https://github.com/extenda/hiiretail-checkout-ui/pull/1595)
[hiiretail-developer-docs PR](https://github.com/extenda/hiiretail-developer-docs/pull/457)
> fix: ComboSale - RegisterWithQuantity rename 

- customer-config/checkout-app/cha.settings.v2.json
[Issue link](https://extendaretail.atlassian.net/browse/HCC-8404)
Tenants should be able to define if they want Numeric or Alphanumeric keyboard as default on the loyalty command
> feat(HCC-8404): Add configuration to support keyboard type based on prompt

- customer-config/attendant-app/att.boolean-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1952
> feat(AT-1952): Add bool config schema

- customer-config/attendant-app/att.boolean-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1952
> fix(AT-1952): Redefine boolean config schema

- customer-config/attendant-app/att.timeout-config.v1.json
Issue: https://extendaretail.atlassian.net/browse/AT-1954
> feat(AT-1954): Add timeout config schema Att

- customer-config/checkout-app/cha.settings.v1.json
[CA original PR](https://github.com/extenda/hiiretail-checkout-ui/pull/1618)
> feat(HCC-10653): add SSLP settings in SCO mode

- customer-config/checkout-app/cha.settings.v1.json
[Original PR: feat(HCC-9878): Stock nearby](https://github.com/extenda/hiiretail-checkout-ui/pull/1591)
> feat(HCC-9785): Add whitelisted filters for variant search
